""" Definitions for all types of objects in boolang
"""


from AST import *


class Function:
    """ Class to represent a boolang function
    """

    expr = Expr    # the actual expression of the function
    variables = [] # a list of all variables in the function

    def __repr__(self):
        return "Function of {}, expr: {}".format(self.variables, self.expr)


    def __init__(self, **kwargs):
        """ Pass the expression generated by the AST and a list of variables
        """
        self.expr = kwargs['expr']
        self.variables = kwargs['variables']


    def evaluate(self, inputs):
        """ Evaluates the function at inputs (dictionary) and returns either
            true or false
        """
        return True


    def truth(self):
        """ Return a string of the truth table for the function
        """
        return self.__repr__()
